[build]
  command = "npx ng build --configuration production --output-mode static --no-ssr && find dist/ -name '*.js' -exec sed -i \"s|__API_URL__|$API_URL|g\" {} +"
  publish = "dist/frontend/browser"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
