FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

COPY pom.xml .
RUN mvn dependency:go-offline -B

COPY src ./src
COPY dev-entrypoint.sh .
RUN chmod +x dev-entrypoint.sh

EXPOSE 8080

CMD ["./dev-entrypoint.sh"]
